/*
 * globals.h
 *
 * Created: 29-Apr-18 16:09:52
 *  Author: abc
 */ 


#ifndef GLOBALS_H_
#define GLOBALS_H_ hh


enum MENU_STATE {NOW_VOLT, NOW_VOLT_B1, NOW_VOLT_B2, SHT_DWN_VOLT, SHT_DWN_VOLT_B1, SHT_DWN_VOLT_B2, SHT_DWN_VOLT_B3, TRN_UP_VOLT, TRN_UP_VOLT_B1, TRN_UP_VOLT_B2, TRN_UP_VOLT_B3, CHNG_TRN_UP_VOLT, CHNG_TRN_UP_VOLT_B1, CHNG_TRN_UP_VOLT_B2, CHNG_TRN_UP_VOLT_B3, CHNG_SHT_DWN_VOLT, CHNG_SHT_DWN_VOLT_B1, CHNG_SHT_DWN_VOLT_B2, CHNG_SHT_DWN_VOLT_B3};

enum BUTTON {TRUE, FALSE};

#endif /* GLOBALS_H_ */